# Only run this pipeline for PRs, so exclude all branches
trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    include:
    - 'main'

jobs:
- job: 'LintMarkdown'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Npm@1
    displayName: 'Install NPM packages'
    inputs:
      command: 'install'

  - task: Npm@1
    displayName: 'Run markdownlint'
    inputs:
      command: 'custom'
      customCommand: 'run --silent lint:markdown'

- job: 'LintCommitMessages'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Npm@1
    displayName: 'Install NPM packages'
    inputs:
      command: 'install'

  - script: |
      # When building a PR, the HEAD commit is actually a merge commit for the
      # merge between the PR branch and the target branch. Because of this we
      # want to ignore this merge commit and look at the previous commit.
      SOURCE_COMMIT=`git rev-parse @^2`

      npx commitlint --config "commitlint-ci.config.js" --from `git rev-parse $TARGET_BRANCH` --to "$SOURCE_COMMIT"
    displayName: 'Lint Commit Messages'
    env:
      TARGET_BRANCH: 'origin/$(System.PullRequest.TargetBranch)'
